// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/buttons/BackButton.vue')['default']
    BaseButton: typeof import('./components/buttons/BaseButton.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Card: typeof import('./components/cards/Card.vue')['default']
    CoingeckoForm: typeof import('./components/forms/CoingeckoForm.vue')['default']
    CoingeckoFormWizard: typeof import('./components/forms/CoingeckoFormWizard.vue')['default']
    DarkModeToggler: typeof import('./components/buttons/DarkModeToggler.vue')['default']
    FooterContainer: typeof import('./components/layout/FooterContainer.vue')['default']
    FormvuelateValidation: typeof import('./components/forms/FormvuelateValidation.vue')['default']
    HamburgerButton: typeof import('./components/buttons/HamburgerButton.vue')['default']
    HamburgerLine: typeof import('./components/buttons/HamburgerLine.vue')['default']
    HeaderContainer: typeof import('./components/layout/HeaderContainer.vue')['default']
    LayoutContainer: typeof import('./components/layout/LayoutContainer.vue')['default']
    Loading: typeof import('./components/layout/Loading.vue')['default']
    NextPageButton: typeof import('./components/buttons/NextPageButton.vue')['default']
    PageHeading: typeof import('./components/text/PageHeading.vue')['default']
    README: typeof import('./components/README.md')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
  }
}

export { }
